---
driver:
  name: terraform

provisioner:
  name: terraform

platforms:
  - name: ubuntu

verifier:
  name: terraform
  reporter: doc
  systems:
    - name: default
      backend: ssh
      user: ubuntu
      hosts_output: public_dns
      key_files:
       - ~/.ssh/id_rsa
      controls:
      - operating_system

suites:
  - name: default
